default_platform(:ios)

platform :ios do
  desc "Install Xcode"
  lane :install_xcode do
    sh "brew install xcodes" # Make sure xcodes is installed
    sh "xcodes install 13.2 --update --select --experimental-unxip --no-progress"
  end
end
